# Generated by Django 3.2 on 2021-05-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0007_mascota_dueno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='dueno',
            field=models.CharField(default='--', max_length=45),
        ),
    ]
