# Generated by Django 3.2 on 2021-05-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0009_galeria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(default='default.png', null=True, upload_to='mascotas'),
        ),
    ]
